import type { ExpertCardProps } from "@/components/ui/ExpertCard";
import type { CourseCardProps } from "@/components/ui/CourseCard";
import type { ProductCardProps } from "@/components/ui/ProductCard";
import type { MapMarkerItem } from "@/components/location/LocationMap";

export const MOCK_EXPERTS: ExpertCardProps[] = [
  {
    id: "exp-1",
    name: "Dr. João Silva",
    title: "Médico Veterinário • Grandes Animais",
    specialty: "Sanidade Bovina, Reprodução e Nutrição Pecuária",
    provinceName: "Huambo",
    municipalityName: "Caála",
    rating: 4.9,
    consultationsCount: 42,
    avatarUrl: null,
    verified: true,
    hourlyRate: "25.000 Kz / hora",
    profileSlug: "dr-joao-silva",
  },
  {
    id: "exp-2",
    name: "Eng.ª Maria Santos",
    title: "Engenheira Agrónoma",
    specialty: "Fertilidade dos Solos, Horticultura e Irrigação Localizada",
    provinceName: "Benguela",
    municipalityName: "Catumbela",
    rating: 5.0,
    consultationsCount: 38,
    avatarUrl: null,
    verified: true,
    hourlyRate: "30.000 Kz / hora",
    profileSlug: "maria-santos-agronoma",
  },
  {
    id: "exp-3",
    name: "Dr. Carlos Manuel",
    title: "Consultor Agrícola & Fitossanitário",
    specialty: "Culturas de Milho, Soja e Controlo Integrado de Pragas",
    provinceName: "Malanje",
    municipalityName: "Cacuso",
    rating: 4.8,
    consultationsCount: 56,
    avatarUrl: null,
    verified: true,
    hourlyRate: "22.000 Kz / hora",
    profileSlug: "carlos-manuel-fitossanidade",
  },
  {
    id: "exp-4",
    name: "Dra. Ana Teresa",
    title: "Especialista em Avicultura e Suinicultura",
    specialty: "Biossegurança, Nutrição de Aves e Gestão de Granjas",
    provinceName: "Luanda",
    municipalityName: "Viana",
    rating: 4.9,
    consultationsCount: 64,
    avatarUrl: null,
    verified: true,
    hourlyRate: "28.000 Kz / hora",
    profileSlug: "dra-ana-teresa",
  },
];

export const MOCK_COURSES: CourseCardProps[] = [
  {
    id: "crs-1",
    title: "Maneio Intensivo e Nutrição de Gado Bovino em Angola",
    instructorName: "Dr. João Silva",
    instructorRole: "Médico Veterinário",
    provinceName: "Huambo",
    durationHours: 16,
    lessonsCount: 22,
    studentsCount: 184,
    priceFormatted: "45.000 Kz",
    level: "Intermédio",
    category: "Pecuária Bovina",
  },
  {
    id: "crs-2",
    title: "Horticultura Comercial e Sistemas de Rega Gota-a-Gota",
    instructorName: "Eng.ª Maria Santos",
    instructorRole: "Engenheira Agrónoma",
    provinceName: "Benguela",
    durationHours: 12,
    lessonsCount: 16,
    studentsCount: 230,
    priceFormatted: "35.000 Kz",
    level: "Iniciante",
    category: "Horticultura",
  },
  {
    id: "crs-3",
    title: "Cultivo e Gestão de Milho em Grande Escala no Planalto Central",
    instructorName: "Dr. Carlos Manuel",
    instructorRole: "Consultor Agrícola",
    provinceName: "Malanje",
    durationHours: 20,
    lessonsCount: 28,
    studentsCount: 145,
    priceFormatted: "50.000 Kz",
    level: "Avançado",
    category: "Grandes Culturas",
  },
  {
    id: "crs-4",
    title: "Gestão Financeira e Rentabilidade para Pequenas Fazendas",
    instructorName: "António Costa",
    instructorRole: "Gestor Agroindustrial",
    provinceName: "Luanda",
    durationHours: 8,
    lessonsCount: 12,
    studentsCount: 310,
    priceFormatted: "25.000 Kz",
    level: "Iniciante",
    category: "Gestão Agrícola",
  },
];

export const MOCK_PRODUCTS: ProductCardProps[] = [
  {
    id: "prd-1",
    title: "Bomba de Irrigação Solar 3HP com Painéis Fotovoltaicos",
    sellerName: "Agro Comercial Angola",
    category: "Equipamentos & Irrigação",
    priceFormatted: "480.000 Kz",
    unit: "conjunto",
    provinceName: "Huíla",
    municipalityName: "Lubango",
    stockAvailable: 12,
    isVerifiedSeller: true,
  },
  {
    id: "prd-2",
    title: "Adubo Composto NPK 12-24-12 (Saco 50kg)",
    sellerName: "Fertilizantes do Sul Lda",
    category: "Fertilizantes & Insumos",
    priceFormatted: "32.000 Kz",
    unit: "saco 50kg",
    provinceName: "Benguela",
    municipalityName: "Lobito",
    stockAvailable: 150,
    isVerifiedSeller: true,
  },
  {
    id: "prd-3",
    title: "Semente de Milho Híbrido Certificada ZM-521 (25kg)",
    sellerName: "Sementes do Planalto",
    category: "Sementes Certificadas",
    priceFormatted: "28.500 Kz",
    unit: "saco 25kg",
    provinceName: "Huambo",
    municipalityName: "Caála",
    stockAvailable: 80,
    isVerifiedSeller: true,
  },
  {
    id: "prd-4",
    title: "Kit de Vacinação e Medicamentos Veterinários Bovinos",
    sellerName: "VetPharma Angola",
    category: "Saúde Animal",
    priceFormatted: "65.000 Kz",
    unit: "kit",
    provinceName: "Luanda",
    municipalityName: "Viana",
    stockAvailable: 25,
    isVerifiedSeller: true,
  },
];

export const MOCK_MAP_MARKERS: MapMarkerItem[] = [
  {
    id: "m-1",
    title: "Dr. João Silva (Veterinário)",
    category: "expert",
    latitude: -12.8525,
    longitude: 15.5606,
    provinceName: "Huambo",
    municipalityName: "Caála",
    description: "Médico veterinário especializado em sanidade animal e reprodução bovina.",
  },
  {
    id: "m-2",
    title: "Eng.ª Maria Santos (Agrónoma)",
    category: "expert",
    latitude: -12.4333,
    longitude: 13.55,
    provinceName: "Benguela",
    municipalityName: "Catumbela",
    description: "Consultoria agronómica, análise de solo e irrigação por gotejamento.",
  },
  {
    id: "m-3",
    title: "Centro de Formação Agrícola do Huambo",
    category: "academy",
    latitude: -12.7833,
    longitude: 15.7333,
    provinceName: "Huambo",
    municipalityName: "Huambo",
    description: "Aulas práticas presenciais e campo demonstrativo de milho e batata.",
  },
  {
    id: "m-4",
    title: "Agro Comercial Angola (Equipamentos)",
    category: "shopping",
    latitude: -14.9167,
    longitude: 13.55,
    provinceName: "Huíla",
    municipalityName: "Lubango",
    description: "Bombas de água solares, alfaias agrícolas e sistemas de rega.",
  },
  {
    id: "m-5",
    title: "Dr. Carlos Manuel (Fitossanidade)",
    category: "expert",
    latitude: -9.4167,
    longitude: 15.75,
    provinceName: "Malanje",
    municipalityName: "Cacuso",
    description: "Controlo de pragas e doenças em culturas extensivas de milho e soja.",
  },
  {
    id: "m-6",
    title: "Fertilizantes do Sul (Distribuidor)",
    category: "shopping",
    latitude: -12.35,
    longitude: 13.5333,
    provinceName: "Benguela",
    municipalityName: "Lobito",
    description: "Distribuição a grosso de adubos NPK e correctivos de solo.",
  },
];
